version: '3.8'

services:
  bitbadges-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    container_name: bitbadges-explorer
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
