version: '3.8'

services:
  bitbadges-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    container_name: bitbadges-explorer
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
