name: Update BitBadges Registry

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering

jobs:
  update-registry:
    runs-on: ubuntu-latest
    environment: Docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create .env file
        run: |
          echo "BITBADGES_API_KEY=${{ secrets.BITBADGES_API_KEY }}" > .env
          echo "BENCHMARK_MODE=false" >> .env

      - name: Run registry generation script
        run: |
          npx tsx scripts/generate-registry.ts

      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet chains/mainnet/bitbadges.json; then
            echo "no-changes=true" >> $GITHUB_OUTPUT
            echo "No changes detected in bitbadges.json"
          else
            echo "no-changes=false" >> $GITHUB_OUTPUT
            echo "Changes detected in bitbadges.json"
          fi

      - name: Create Pull Request
        if: steps.check-changes.outputs.no-changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update bitbadges registry assets"
          title: "🔄 Update BitBadges Registry Assets"
          body: |
            ## 🤖 Automated Registry Update
            
            This PR was automatically generated to update the BitBadges registry assets.
            
            ### Changes Made:
            - Updated `chains/mainnet/bitbadges.json` with latest asset information
            - Generated from BitBadges API data
            
            ### Generated by:
            - GitHub Actions workflow: `update-registry.yaml`
            - Script: `scripts/generate-registry.ts`
            - Environment: Docker container
            
            ---
            
            **Note:** This is an automated PR. Please review the changes before merging.
          branch: update-registry-assets
          delete-branch: true
          base: main
          labels: |
            automated
            registry-update
            dependencies 